services:
  _defaults:
    public: true

  pda_customer_repository:
    class: mymodule\Repository\PDACustomerRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'